App\Entity\User:
    type: entity
    #repositoryClass: App\Repository\UserRepository 
    table: user
    # indexes:
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        plainPassword:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        password:
            type: text
            length: 4096
            column: plain_password                
        firstName:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: last_name
#    manyToOne:
    oneToMany:
        userRoles:
            targetEntity: UserRole
            mappedBy: user
    lifecycleCallbacks: {  }