# config/doctrine/AppConfigOptions.orm.yml
App\Entity\AppConfigOptions:
    type: entity
    #repositoryClass: App\Repository\AppConfigOptionsRepository
    table: app_config_options  
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        option:
            type: string
            length: 100
            nullable: true
            unique: true    
    manyToOne:      
        appConfig:
            targetEntity: App\Entity\AppConfig       
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: appConfigOptionsList
            joinColumns:
                app_config:
                    referencedColumnName: id
            orphanRemoval: false