# config/doctrine/AppConfig.orm.yml
App\Entity\AppConfig:
    type: entity
    # repository ######################################################     
    #repositoryClass: App\Repository\AppConfigRepository
    table: app_config
    indexes:
        option:
            columns:
                - option    
# indexes #############################################################     
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
# /id #################################################################
# fields ##############################################################                
    fields:
        name:
            type: string
            length: 150
            nullable: false
            unique: false
            column: name  
        type:
            type: string
            length: 30
            nullable: false
            unique: false
            column: type                                
# /fields #############################################################
# manyToOne ###########################################################          
    manyToOne:      
        options:
            targetEntity: App\Entity\AppConfigOptions      
            cascade: {  }
            fetch: LAZY
            nullable: true
            mappedBy: null
            inversedBy: null
            joinColumns:
                options:
                    referencedColumnName: id
            orphanRemoval: false
# /manyToOne ##########################################################            
# oneToMany ###########################################################               
    oneToMany:
        # appConfigTaxonomyList # no se encuentra dentro de la BD, pero se define en la entidad para listar los elementos
        appConfigOptionsList:
            targetEntity: App\Entity\AppConfigOptions
            mappedBy: appConfig
# /oneToMany ##########################################################               
    lifecycleCallbacks: {  }                        