register:
    path: /api/signup
    controller: App\Controller\SecurityController::signup
    methods: POST

api:
    path: /api
    controller: App\Controller\SecurityController::api

api_login_check:
    path: /api/login_check
    #methods:  [POST]